// Some crypto/error-path entries set `sanitizeResources: false`. On Deno, these tests take an
// error/abort path that cancels a stream transferred to the codec worker, and Deno leaks that
// transferred ReadableStream's underlying MessagePort on cancel (draining to completion does not
// leak). It is a Deno resource-sanitizer bug, not a zip.js one — nothing in JS closes the port —
// so the sanitizer is opted out only for the affected tests. See denoland/deno#36015 (repro in
// benchmarks/deno-messageport-leak.test.mjs, still reproduced with deno 2.9.5).
export default ([
	{ title: "Abort signal (read)", script: "./test-abort-signal-read.js" },
	{ title: "Abort signal (worker reuse)", script: "./test-worker-reuse-after-abort.js" },
	{ title: "Abort signal (write)", script: "./test-abort-signal-write.js" },
	{ title: "Abort signal (buffered flush offset)", script: "./test-abort-buffered-flush-offset.js" },
	{ title: "Append to zip", script: "./test-append-to-zip.js" },
	{ title: "Append to zip (central directory metadata)", script: "./test-prepend-zip-metadata.js" },
	{ title: "Append to zip (compression level bits)", script: "./test-prepend-zip-level-bits.js" },
	{ title: "Uint8Array", script: "./test-array.js" },
	{ title: "Arraybuffer", script: "./test-arrayBuffer.js" },
	{ title: "Filesystem getArrayBuffer", script: "./test-fs-array-buffer.js" },
	{ title: "Base 64", script: "./test-base64.js" },
	{ title: "Ambiguity check", script: "./test-check-ambiguity.js" },
	{ title: "End of central directory selection", script: "./test-end-of-central-directory.js" },
	{ title: "Malformed zip files", script: "./test-malformed-zip.js" },
	{ title: "Invalid chunk size configuration", script: "./test-config-chunk-size.js" },
	{ title: "Writer edge cases", script: "./test-writer-edge-cases.js" },
	{ title: "Writer streaming backpressure", script: "./test-writer-backpressure.js" },
	{ title: "Writer JS codec fallback on WASM load failure", script: "./test-writer-js-codec-fallback.js" },
	{ title: "IO edge cases", script: "./test-io-edge-cases.js" },
	{ title: "Blob", script: "./test-blob.js" },
	{ title: "Comments", script: "./test-comments.js" },
	{ title: "Compression method and level", script: "./test-compression-method-level.js" },
	{ title: "Common JS", script: "./test-common-js.cjs", env: ["node"] },
	{ title: "Core", script: "./test-core.js" },
	{ title: "Crypto", script: "./test-crypto.js", sanitizeResources: false },
	{ title: "Crypto (raw password)", script: "./test-crypto-raw-password.js" },
	{ title: "Crypto check password only", script: "./test-crypto-check-password.js", sanitizeResources: false },
	{ title: "Crypto tampered data", script: "./test-crypto-tampered.js" },
	{ title: "Crypto AES streaming", script: "./test-aes-streaming.js" },
	{ title: "Custom IO classes", script: "./test-custom-io.js" },
	{ title: "Custom temp stream", script: "./test-custom-temp-buffer.js" },
	{ title: "Custom temp stream (concurrent add)", script: "./test-concurrent-add-temp-stream.js" },
	{ title: "Temp stream dispose hook", script: "./test-temp-stream-dispose.js" },
	{ title: "OPFS temp stream", script: "./test-opfs-temp-stream.js" },
	{ title: "Blob temp stream", script: "./test-blob-temp-stream.js" },
	{ title: "Sync access handle temp stream", script: "./test-sync-access-handle-temp-stream.js" },
	{ title: "OPFS temp stream (real OPFS)", script: "./test-opfs-temp-stream-browser.js", env: ["browser"] },
	{ title: "Keep order (concurrent add)", script: "./test-keep-order-concurrent.js" },
	{ title: "Data descriptor signature", script: "./test-data-descriptor-signature.js" },
	{ title: "Data descriptor", script: "./test-data-descriptor.js" },
	{ title: "Data URI", script: "./test-data-uri.js" },
	{ title: "Data URI (small chunks)", script: "./test-data-uri-chunks.js" },
	{ title: "Deflate64", script: "./test-deflate64.js" },
	{ title: "Deflate64 (length code 285)", script: "./test-deflate64-length-code-285.js" },
	{ title: "Detect directory executable", script: "./test-detect-directory-exec.js" },
	{ title: "Directory", script: "./test-directory.js" },
	{ title: "Directory flag (unicode path override)", script: "./test-directory-flag-unicode-path.js" },
	{ title: "Executable", script: "./test-executable.js" },
	{ title: "Duplicated Filename", script: "./test-duplicated-filename.js" },
	{ title: "Empty zip file", script: "./test-empty.js" },
	{ title: "Entry count from total field", script: "./test-entry-count-total.js" },
	{ title: "Extended timestamp", script: "./test-extended-timestamp.js" },
	{ title: "Extra field", script: "./test-extra-field.js" },
	{ title: "Last access date and creation date", script: "./test-last-access-date.js" },
	{ title: "Filesystem base 64", script: "./test-fs-base64.js" },
	{ title: "Filesystem check password", script: "./test-fs-check-password.js", sanitizeResources: false },
	{ title: "Filesystem export", script: "./test-fs-export-options.js" },
	{ title: "Filesystem export error", script: "./test-fs-export-error.js" },
	{ title: "Filesystem export zip", script: "./test-fs-export-zip.js" },
	{ title: "Filesystem export File System handle", script: "./test-fs-export-file-system-handle.js" },
	{ title: "Filesystem export File System handle (real OPFS)", script: "./test-fs-export-file-system-handle-browser.js", env: ["browser"] },
	{ title: "Filesystem find (verbatim slash name)", script: "./test-fs-find-slash-name.js" },
	{ title: "Filesystem HTTP import", script: "./test-fs-http-import.js" },
	{ title: "Filesystem import edge cases", script: "./test-fs-import-edge-cases.js" },
	{ title: "Filesystem remove", script: "./test-fs-remove.js" },
	{ title: "Filesystem deep tree", script: "./test-fs-deep-tree.js" },
	{ title: "Filesystem HTTP reader", script: "./test-fs-http-reader.js" },
	{ title: "Filesystem metadata", script: "./test-fs-metadata.js" },
	{ title: "Filesystem passthrough", script: "./test-fs-passthrough.js" },
	{ title: "Filesystem replace entry", script: "./test-fs-replace.js" },
	{ title: "Filesystem streams", script: "./test-fs-streams.js" },
	{ title: "Filesystem text", script: "./test-fs-text.js" },
	{ title: "Filesystem unzip uncompressed file", script: "./test-fs-unzip-store.js" },
	{ title: "Filesystem test", script: "./test-fs.js" },
	{ title: "HTTP crypto", script: "./test-http-crypto.js" },
	{ title: "HTTP range (ZipWriter#add)", script: "./test-http-range-writer-add.js", env: ["browser"] },
	{ title: "HTTP range", script: "./test-http-range.js", env: ["browser"] },
	{ title: "HTTP split file", script: "./test-http-split-zip.js" },
	{ title: "HTTP zip64", script: "./test-http-zip64.js" },
	{ title: "HTTP reader (custom fetch)", script: "./test-http-reader-custom-fetch.js" },
	{ title: "HTTP reader (resource changed)", script: "./test-http-reader-resource-changed.js" },
	{ title: "HTTP range requests", script: "./test-http-range-requests.js" },
	{ title: "Writer exact chunks", script: "./test-writer-exact-chunks.js" },
	{ title: "Invalid CRC", script: "./test-invalid-crc.js" },
	{ title: "Invalid uncompressed size", script: "./test-invalid-uncompressed-size.js", sanitizeResources: false },
	{ title: "Multiple writers", script: "./test-multiple-writers.js" },
	{ title: "MS-DOS attributes", script: "./test-msdos-attributes.js" },
	{ title: "No worker", script: "./test-no-worker.js" },
	{ title: "Overlapping entries only", script: "./test-overlapping-entries-only.js" },
	{ title: "Overlapping entries", script: "./test-overlapping-entries.js" },
	{ title: "Overlapping entries (contained)", script: "./test-overlapping-entries-contained.js" },
	{ title: "Parallel reads", script: "./test-parallel-reads.js" },
	{ title: "Parallel writes (auto buffered)", script: "./test-parallel-writes-auto-buffered.js" },
	{ title: "Parallel writes (ordered)", script: "./test-parallel-writes-ordered.js" },
	{ title: "Parallel writes", script: "./test-parallel-writes.js" },
	{ title: "Pass through", script: "./test-passthrough.js" },
	{ title: "Pass through crypto", script: "./test-passthrough-crypto.js" },
	{ title: "Pass through uncompressed data", script: "./test-passthrough-uncompressed.js" },
	{ title: "Pass through zipcrypto", script: "./test-passthrough-zipcrypto.js" },
	{ title: "Pass through zstd", script: "./test-passthrough-zstd.js" },
	{ title: "Prepended data with zip64 offsets", script: "./test-prepended-data-zip64.js" },
	{ title: "Zip64 offset boundaries", script: "./test-zip64-offset-boundary.js" },
	{ title: "Worker loading error", script: "./test-worker-error.js", sanitizeResources: false },
	{ title: "Props", script: "./test-props.js" },
	{ title: "Readable Stream", script: "./test-readable-stream.js" },
	{ title: "Readable Zip Stream", script: "./test-readable-zip-stream.js" },
	{ title: "Remove entry", script: "./test-remove-entry.js" },
	{ title: "Replace entry", script: "./test-replace-entry.js" },
	{ title: "Safe closing", script: "./test-safe-closing.js" },
	{ title: "Service worker", script: "./test-sw.js", env: ["browser"] },
	{ title: "Web worker", script: "./test-web-worker.js", env: ["browser", "deno", "bun"] },
	{ title: "Signature CRC32", script: "./test-crc.js" },
	{ title: "Split data", script: "./test-split-data.js" },
	{ title: "Split zip file", script: "./test-split-zip.js" },
	{ title: "Split zip file (segment boundaries)", script: "./test-split-zip-boundaries.js" },
	{ title: "Split zip file (corrupted entry)", script: "./test-split-corrupted-entry.js" },
	{ title: "Split zip file (zip64 boundaries)", script: "./test-split-zip64-boundaries.js" },
	{ title: "Golden output", script: "./test-golden-output.js" },
	{ title: "Store", script: "./test-store.js" },
	{ title: "Streams", script: "./test-streams.js" },
	{ title: "Text encoding ", script: "./test-text-encoding.js" },
	{ title: "Unicode file names", script: "./test-use-unicode-file-names.js" },
	{ title: "Text UNIX metadata", script: "./test-unix-metadata.js" },
	{ title: "Text UNIX extra field layout", script: "./test-unix-extra-field-layout.js" },
	{ title: "Text UNIX special bits (no mode)", script: "./test-unix-special-bits-no-mode.js" },
	{ title: "Text UNIX special bits", script: "./test-unix-special-bits.js" },
	{ title: "Text UNIX unpack", script: "./test-unix-unpack.js" },
	{ title: "USDZ", script: "./test-usdz.js" },
	{ title: "Worker starvation", script: "./test-worker-starvation.js" },
	{ title: "Worker timeout", script: "./test-worker-timeout.js" },
	{ title: "Wrapped zip file", script: "./test-wrapped.js" },
	{ title: "Writable Stream", script: "./test-writable-stream.js" },
	{ title: "Zip Streams", script: "./test-zip-streams.js" },
	{ title: "Zip64 (auto)", script: "./test-zip64-auto.js", env: ["deno", "browser"] },
	{ title: "Zip64 (buffered, no data descriptor)", script: "./test-zip64-buffered-no-data-descriptor.js" },
	{ title: "Zip64 (buffered)", script: "./test-zip64-buffered.js" },
	{ title: "Zip64 crypto", script: "./test-zip64-crypto.js" },
	{ title: "Zip64 (no compression)", script: "./test-zip64-no-compression.js" },
	{ title: "Zip64 (local compressed size)", script: "./test-zip64-local-compressed-size.js" },
	{ title: "Zip64 (passthrough)", script: "./test-zip64-passthrough.js" },
	{ title: "Zip64 (streamed local extra field)", script: "./test-zip64-stream-local-field.js" },
	{ title: "Zip64", script: "./test-zip64.js" },
	{ title: "Zipcrypto", script: "./test-zipcrypto.js", sanitizeResources: false }
]);