# .github/workflows/publish.yml

name: Publish

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  publish_jsr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: npx jsr publish

  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish

  publish_docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/checkout@v5
        with:
          ref: gh-pages
          path: gh-pages
      - uses: actions/setup-node@v5
        with:
          node-version: '24'
      - run: npm ci
      - run: npx typedoc --out gh-pages/api
      - run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add api
          git diff --cached --quiet || { git commit -m "update api doc"; git push; }
